### ISSUE TITLE
Homepage | hero banner slider - side black space

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#100]
Black space is appearing on the sides of the hero banner slider.
Check the below link for better understanding.
https://www.screencast.com/t/tuQulMtm17

**Comment by Gaurav-Quadrish** [comment]
I have fixed this issue please check it.

**Comment by Priya-Quadrish** [comment]
Issue is still pending.

![image](https://user-images.githubusercontent.com/51991326/64593700-22ac0a00-d3cc-11e9-862f-e894aeccde44.png)
![image](https://user-images.githubusercontent.com/51991326/64593750-36f00700-d3cc-11e9-9153-a95c3834d0ca.png)

**Comment by Gaurav-Quadrish** [comment]
this issue is already assigned in ticket no 86
