### ISSUE TITLE
Case study page 

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#103]
Align the content a little towards the right-hand side.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/105a2cad-2187-4658-9b7a-df178339e07e)

**Comment by Priya-Quadrish** [comment]
Issue is still the same.
![image](https://user-images.githubusercontent.com/51991326/65015539-7a53f380-d93f-11e9-87e1-62c1a68b2bf5.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed it now. please check.
![case-studies](https://user-images.githubusercontent.com/52441095/65021409-a9bd2d00-d94c-11e9-8fdc-44e5486516f9.png)

**Comment by Priya-Quadrish** [comment]
The issue is still the same.
Fix the above-mentioned issue for all the responsive screens.

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
