### ISSUE TITLE
Mobile view  |  Homepage  |  Hero banner image

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#16]
Hero banner images of home page is cropping in small screens view – it must be adjusted according to the screen sizes.(that is;  full images should be visible in mobile view too)
![24.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/6a986fa3-205f-4f6e-afa1-c9d3df31f58f)

**Comment by Gaurav-Quadrish** [comment]
i fixed it for all mobiles and iPad media screen sizes.
![1](https://user-images.githubusercontent.com/52441095/63412480-7783e280-c415-11e9-8c09-d489adc8fd78.png)

**Comment by Priya-Quadrish** [comment]
Issue is still pending.
Hero banner must cover the full first page screen.
![image](https://user-images.githubusercontent.com/51991326/63428066-42d35380-c434-11e9-9519-203d386c2b68.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue for mobile view.

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
