### ISSUE TITLE
Page: All | View: Mobile | Change footer style

### ISSUE THREAD

**Issue by Sukhvir-Quadrish** [Quadrish/Quadrish-Website#19]
Please change the footer style 
from:
![image.png](https://images.zenhubusercontent.com/5c8caf06d74bd07972c7f03c/57ae4018-03ce-42cc-b647-5797d52c7135)

To:
![image.png](https://images.zenhubusercontent.com/5c8caf06d74bd07972c7f03c/f58faeed-74cd-4b92-a0a7-43f74dd19bcb)

We need to do two things:

1. Set the three option "Grid View" instead of "List view" on i mentioned in second screenshot on 1,2,3 position with red color.
2. Set the condition when resolution like above screenshot then "Privacy Policy" link should be in one line, i mentioned it with yellow color.

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue. 
![footer](https://user-images.githubusercontent.com/52441095/62595567-7c687280-b8fc-11e9-9635-6aafde532e2b.png)

**Comment by Priya-Quadrish** [comment]
1. Place the instagram icon properly(at the center, above the copyright line)
2. Add thin grey/white vertical line in the footer and shift the content a little towards the R.H.S.

![image](https://user-images.githubusercontent.com/51991326/62916432-0fe6eb00-bdb6-11e9-90ea-60a4503db918.png)

![image](https://user-images.githubusercontent.com/51991326/62916529-7bc95380-bdb6-11e9-9079-16edc21adc3d.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue in ticket 19.
![Untitled](https://user-images.githubusercontent.com/52441095/62933525-007c9780-bde0-11e9-9a6e-50686d68498f.png)

**Comment by Priya-Quadrish** [comment]
Design the footer for mobile according to the image below.(for all mobile screens)
![image](https://user-images.githubusercontent.com/51991326/62996488-86511f00-be82-11e9-9aff-cdc2f0517a89.png)

**Comment by Gaurav-Quadrish** [comment]
I re-design the the footer section according to the above image. 
![Untitled](https://user-images.githubusercontent.com/52441095/63146576-fbeef380-c018-11e9-8841-e6483280064c.png)

**Comment by Priya-Quadrish** [comment]
Make the footer responsive with all the screen sizes.
![image](https://user-images.githubusercontent.com/51991326/63427645-3c90a780-c433-11e9-8f0a-562d09f83e40.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue.
![social-icon](https://user-images.githubusercontent.com/52441095/64238072-4f1edc80-cf1b-11e9-8a1a-3fa8825816a8.png)

**Comment by Priya-Quadrish** [comment]
For small screens - footer alignment issue is still present.

![image](https://user-images.githubusercontent.com/51991326/64314099-63baad80-cfcb-11e9-83c4-dc370230702e.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed it .
![footer](https://user-images.githubusercontent.com/52441095/64755526-d1755500-d548-11e9-802a-b222a61bc9fa.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
