### ISSUE TITLE
All pages | Banner images

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#2]
All the banner images are not related with the content in that particular page/section  ; so better if we just use the color background or those images which relates to the page.![2.bmp.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/358a62c9-8644-457b-9e01-5fc71981f8db)

**Comment by Gaurav-Quadrish** [comment]
I used the default background color for the **title box** 
![Screenshot_2019-07-03 Portfolio – Quadrish](https://user-images.githubusercontent.com/52441095/60591356-f36d9100-9dbb-11e9-9fbe-b78f44124123.png)

**Comment by Priya-Quadrish** [comment]
Add some opacity to the hero banner of inner pages.
Also, make the text vertically centered.
![2019-07-03_1759](https://user-images.githubusercontent.com/51991326/60591737-b655ce80-9dbc-11e9-9ce6-dbe0194854f8.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed the opacity and position issue of page title,
![Screen Shot 2019-07-03 at 10 34 27](https://user-images.githubusercontent.com/52441095/60664760-54f73380-9e80-11e9-8f4f-f1dffbe63fe3.png)

**Comment by Priya-Quadrish** [comment]
Text is still not vertically centered.
Also, make the shade of background similar with the shared screenshot below.

![2](https://user-images.githubusercontent.com/51991326/60667100-4dd32400-9e86-11e9-9266-fdc3f462dd7f.png)
![3](https://user-images.githubusercontent.com/51991326/60667101-4e6bba80-9e86-11e9-939c-e17727155734.png)

**Comment by Gaurav-Quadrish** [comment]
fixed the title position ![page-title](https://user-images.githubusercontent.com/52441095/60721797-b389e380-9f4c-11e9-96cb-38c89ac5bbec.png)

**Comment by Priya-Quadrish** [comment]
Still the hero banner image shade is not matching with the provided one.

**Comment by Gaurav-Quadrish** [comment]
please check now
![Screenshot_2019-07-03 About – Quadrish(1)](https://user-images.githubusercontent.com/52441095/60722243-eed8e200-9f4d-11e9-9fd5-26a41e90a732.png)

**Comment by Priya-Quadrish** [comment]
Text is still not aligned as vertically centered.
![c](https://user-images.githubusercontent.com/51991326/60722692-4cb9f980-9f4f-11e9-9155-7646cb84498a.png)

**Comment by Gaurav-Quadrish** [comment]
now its vertically center 
![Screen Shot 2019-07-03 at 10 37 02](https://user-images.githubusercontent.com/52441095/60723261-ce5e5700-9f50-11e9-9f38-ff73473318b3.png)

**Comment by Priya-Quadrish** [comment]
Issue is still pending,  make changes for all the responsive (all mobile screen sizes) screens.

![1 1](https://user-images.githubusercontent.com/51991326/60784352-389f1380-a16c-11e9-83e9-9879437291c9.png)

**Comment by Gaurav-Quadrish** [comment]
i fix this issue for every media screen size. 
![Screen Shot 2019-07-08 at 16 42 53](https://user-images.githubusercontent.com/52441095/60951236-51e3c380-a316-11e9-87bd-55152379d3bd.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
