### ISSUE TITLE
Mobile  |  Landscape view  | Footer

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#28]
Links are missing.
Check the below image .

![1.7.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/217a284c-3e18-4f56-ae1c-d9a7eee6c4c5)

**Comment by Gaurav-Quadrish** [comment]
i fixed the footer links and its working fine now..

**Comment by Priya-Quadrish** [comment]
One of the link is still missing.

![1 8](https://user-images.githubusercontent.com/51991326/60810729-5cce1500-a1ab-11e9-9f29-8541b8d0e468.png)

**Comment by Gaurav-Quadrish** [comment]
![skype-link](https://user-images.githubusercontent.com/52441095/60868039-bc7afd80-a249-11e9-81b1-08deb567a2c3.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
