### ISSUE TITLE
Stories  |  Client's visit page

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#51]
Update the client visit content-date and images and shift the content at the top.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/7102cd8a-581d-4c11-91f2-8aeb7c245a94)

**Comment by Gaurav-Quadrish** [comment]
I updated the content please check.
![client-visit](https://user-images.githubusercontent.com/52441095/62366195-defbf000-b543-11e9-9e82-ceab351370f4.png)

**Comment by Priya-Quadrish** [comment]
Shift the images with the older one, do not add extra space between them.
Also, move the latest date of the client's visit first then the previous one.
![image](https://user-images.githubusercontent.com/51991326/62445558-1f46b280-b77e-11e9-80f9-76307b93ba7e.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed it..
![client-visit-page](https://user-images.githubusercontent.com/52441095/62460091-ad329580-b79e-11e9-9144-d713e544a468.png)

**Comment by Priya-Quadrish** [comment]
Spacing issue is still pending.
Also , the image size /resolution must be same.
![image](https://user-images.githubusercontent.com/51991326/62514906-48c71300-b83e-11e9-8f1e-28f9f9474c1a.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed the spacing issue. ![Untitled](https://user-images.githubusercontent.com/52441095/62526116-3e187800-b856-11e9-838e-07742af4db1a.png)

**Comment by Priya-Quadrish** [comment]
Image resolution is still not matching with the other ones.
Also, add the previous visits images too.(they are missing)
![image](https://user-images.githubusercontent.com/51991326/62595788-63ac8c80-b8fd-11e9-9eb9-e59e705c2e50.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed the image resolution.

**Comment by Priya-Quadrish** [comment]
You have removed the images which are not matching the resolution.
I haven't said to remove them.
Show all those images, you just have to match the view and resolution of them with others.
Also ,show the previous visit images too.

**Comment by Priya-Quadrish** [comment]
Events page : image resolution is fixed.
Make the ; client visit page > image section's resolution : similar with it and add all the previous images too.

**Comment by Gaurav-Quadrish** [comment]
I fixed the images resolution issue and also uploaded previous images.
![Untitled](https://user-images.githubusercontent.com/52441095/62763997-7f08ca80-baaa-11e9-83f2-0109c9d3b922.png)

**Comment by Priya-Quadrish** [comment]
Not all the previous images are added.

**Comment by Gaurav-Quadrish** [comment]
I added the old images.
![client-visit](https://user-images.githubusercontent.com/52441095/63768812-d1d9e300-c8ee-11e9-8278-9c96fccac478.png)

**Comment by Priya-Quadrish** [comment]
Add the images of the previous visit of imtiaz too.

![image](https://user-images.githubusercontent.com/51991326/63826429-8837d980-c97c-11e9-9b0e-5eea280e3a47.png)

**Comment by Gaurav-Quadrish** [comment]
i added the previous image ,,

**Comment by Priya-Quadrish** [comment]
Just one image(of previous visit is added ), add more images(2-3) of previous visit of imtiaz

**Comment by Gaurav-Quadrish** [comment]
I have no more images.

**Comment by Priya-Quadrish** [comment]
okay, if you get some old images, add them to the page.
