### ISSUE TITLE
Homepage  |  Hero banner image

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#6]
Maintain the responsive of hero banner image.
Also, reduce the size of the hero banner image in mobile view – as the hero banner should not be shorter of greater than the first screen view width.
![7.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/bc1f29db-4ae1-4f5e-b8bb-adcf9e7eed7a)

**Comment by Gaurav-Quadrish** [comment]
i fixed it in ticket no. 16

**Comment by Priya-Quadrish** [comment]
Issue is still pending.
it must cover the first screen page.
![image](https://user-images.githubusercontent.com/51991326/63428130-6dbda780-c434-11e9-8221-4effa2466be5.png)

**Comment by Gaurav-Quadrish** [comment]
Am not understand please explain it.
![1](https://user-images.githubusercontent.com/52441095/63430516-64cfd480-c43a-11e9-8f6d-46ef1ca00ba0.png)

**Comment by Priya-Quadrish** [comment]
The hero banner image should always display on the first full screen whether it is desktop, mobile, ipad, etc 
sharing the example with you of a separate project's hero banner image.
Check the below link for better understanding.
https://www.screencast.com/t/I1eHaF7RcL

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue in ticket no. 16

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
