### ISSUE TITLE
Story page  |  Client's visit page  |  Image issue

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#63]
Align the image and remove the extra spacing.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/06f9ad0e-a9a5-4e1e-a9b0-0e3ecaee903f)

**Comment by Gaurav-Quadrish** [comment]
i fixed space issue. 
![Screenshot_2019-07-31 Quadrish - Innovations Private Limited(2)](https://user-images.githubusercontent.com/52441095/62450427-ef9da780-b789-11e9-8172-2ba32253d503.png)

**Comment by Priya-Quadrish** [comment]
This issue is still pending.
![image](https://user-images.githubusercontent.com/51991326/62514173-fe449700-b83b-11e9-8077-143130d6ede8.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed it in ticket number #51

**Comment by Priya-Quadrish** [comment]
Spacing issue is done but the image issue is still pending, check the latest comment on ticket 51 .

**Comment by Gaurav-Quadrish** [comment]
I resize the image size for that particular section. 
![Untitled](https://user-images.githubusercontent.com/52441095/62602620-c1e36a80-b911-11e9-8a15-e5ffadcbc107.png)

**Comment by Priya-Quadrish** [comment]
Align the images with the text-paragraph.
![image](https://user-images.githubusercontent.com/51991326/62683764-e1939500-b9dc-11e9-8835-848f9a8082bc.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue.
![Untitled](https://user-images.githubusercontent.com/52441095/62763845-246f6e80-baaa-11e9-8ddc-52403f3698f5.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
