### ISSUE TITLE
Services page  |  Sub category pages

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#65]
Remove the extra spacing and align the content according to it.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/3dbd8f2d-810f-46e3-aebc-0e2965c01477)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue. 
![Screenshot_2019-07-31 Quadrish - Innovations Private Limited](https://user-images.githubusercontent.com/52441095/62449308-8452d600-b787-11e9-92ee-75aaab2e74ae.png)

**Comment by Priya-Quadrish** [comment]
Spacing issue and content alignment issue is still pending.
Check this for all the responsive screens.
![image](https://user-images.githubusercontent.com/51991326/62513907-24b60280-b83b-11e9-80c1-e03fc31b7ce3.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue.
![2](https://user-images.githubusercontent.com/52441095/62620174-33cdab00-b936-11e9-9002-082518259cbd.png)

**Comment by Priya-Quadrish** [comment]
increase the image size for small screens.
![image](https://user-images.githubusercontent.com/51991326/62687270-148d5700-b9e4-11e9-812f-5761a30ce2d6.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed image size issue for every media screen sizes.
![Untitled](https://user-images.githubusercontent.com/52441095/62700467-9a6acb80-b9ff-11e9-889b-d8db71a41d46.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
